### ISSUE TITLE
"This setting cannot be applied in this workspace. It will be applied when you open the containing workspace folder directly."

### ISSUE THREAD

**Issue by nkdmSum** [Gruntfuggly/virtual-folders#3]
I tried using this, but when I pasted the config into settings.json, It was grazed out and when hovering over it, it said:
"This setting cannot be applied in this workspace. It will be applied when you open the containing workspace folder directly."
Here's my sample workspace:
<img width="204" alt="Снимок экрана 2020-07-09 в 19 43 27" src="https://user-images.githubusercontent.com/51021475/87072671-7bcb1100-c21c-11ea-87f2-fba7141d41ce.png">

**Comment by nkdmSum** [comment]
Just realised that this was not updated in 3 years..

**Comment by nkdmSum** [comment]
Pasting it into .code-workspace makes vs let it pass(it's not gray anymore), but the files are still not divided.

**Comment by Gruntfuggly** [comment]
Hi, yeh, it's ben a long time since I used this. I'll try and have a look to see what's going on.

**Comment by nkdmSum** [comment]
Hmm... It works now! Probably was my computer being buggy or something. Thanks for the efforts @Gruntfuggly
